name: Test changelog generator
on:
  push:
    branches:
      - '**'
    paths:
      - .github/workflows/test-changelog-generator.yml
      - .github/generate-changelog/**
  schedule:
    - cron: 0 7 * * 6

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .github/generate-changelog
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        name: Set up node
        with:
          cache: npm
          node-version: 18
          registry-url: https://npm.pkg.github.com
          cache-dependency-path: .github/generate-changelog/package-lock.json
      - name: Install deps
        run: npm ci --no-fund
      - name: Generate changelog
        run: node index.js
